apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: example-distributedrediscluster
  labels:
    # 监控&日志相关的labels
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: example-distributedrediscluster
    app.kubernetes.io/version: "5.0"
    app.kubernetes.io/managed-by: jvessel
spec:
  # Add fields here
  serviceName: redis-svc
  masterSize: 3
  clusterReplicas: 1
  #image: redis:5.0.7-alpine
  image: caiyuanrui-cn-north-1.jcr.service.jdcloud.com/demo/redis:5.0.7-alpine
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi
  monitor:
    #image: oliver006/redis_exporter
    image: caiyuanrui-cn-north-1.jcr.service.jdcloud.com/demo/redis-exporter:latest
  config:
    activerehashing: "yes"
    appendfsync: everysec
    appendonly: "yes"
    hash-max-ziplist-entries: "512"
    hash-max-ziplist-value: "64"
    hll-sparse-max-bytes: "3000"
    list-compress-depth: "0"
    maxmemory-policy: noeviction
    maxmemory-samples: "5"
    no-appendfsync-on-rewrite: "no"
    notify-keyspace-events: ""
    set-max-intset-entries: "512"
    slowlog-log-slower-than: "10000"
    slowlog-max-len: "128"
    stop-writes-on-bgsave-error: "yes"
    tcp-keepalive: "0"
    timeout: "0"
    zset-max-ziplist-entries: "128"
    zset-max-ziplist-value: "64"