apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: example-distributedrediscluster
  name: monitoring-example-distributedrediscluster
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9100"
spec:
  ports:
    - name: http
      port: 9100
      targetPort: 9100
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: example-distributedrediscluster
